version: '3'

services:
  home-hub:
    image: redkite/home-hub
    container_name: home-hub
    ports:
      - 2001:2001
    volumes:
      - ./configs/:/usr/local/etc:ro
    restart: unless-stopped
